import Vue from 'vue';
import Vuetify, {
  VApp,
  VBtn,
  VCard,
  VCardActions,
  VCardText,
  VCardTitle,
  VContainer,
  VContent,
  VDivider,
  VExpansionPanel,
  VExpansionPanelContent,
  VFlex,
  VIcon,
  VImg,
  VItem,
  VItemGroup,
  VLayout,
  VList,
  VListTile,
  VListTileAction,
  VListTileAvatar,
  VListTileContent,
  VListTileTitle,
  VNavigationDrawer,
  VProgressCircular,
  VSelect,
  VSpacer,
  VSnackbar,
  VTextField,
  VToolbar,
  VToolbarSideIcon,
  VToolbarTitle,
} from 'vuetify/lib';
import 'material-design-icons-iconfont';
import 'vuetify/dist/vuetify.min.css';

Vue.use(Vuetify, {
  components: {
    VApp,
    VBtn,
    VCard,
    VCardActions,
    VCardText,
    VCardTitle,
    VContainer,
    VContent,
    VDivider,
    VExpansionPanel,
    VExpansionPanelContent,
    VFlex,
    VIcon,
    VImg,
    VItem,
    VItemGroup,
    VLayout,
    VList,
    VListTile,
    VListTileAction,
    VListTileAvatar,
    VListTileContent,
    VListTileTitle,
    VNavigationDrawer,
    VProgressCircular,
    VSelect,
    VSpacer,
    VSnackbar,
    VTextField,
    VToolbar,
    VToolbarSideIcon,
    VToolbarTitle,
  },
  customProperites: true,
  iconfont: 'md',
});
